-- Experiences (P15): AppExperience + AppExperienceStep.
--
-- NOTE: Prisma's diff engine cannot see the pgvector / tsvector indexes and the
-- `ai_knowledge_chunk.searchVector` generated default (they are raw-SQL, applied by an earlier
-- migration and invisible to the Prisma schema). Every autogenerated app migration therefore
-- proposes dropping them. Those statements were removed by hand. Verify the 5 vector indexes
-- (idx_ai_knowledge_chunk_search_vector, idx_knowledge_embedding, idx_message_embedding,
-- idx_app_data_slot_embedding, idx_app_question_slot_embedding) still exist after applying.

-- CreateTable
CREATE TABLE "app_experience" (
    "id" TEXT NOT NULL,
    "demoClientId" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "kind" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'draft',
    "continuityMode" TEXT NOT NULL DEFAULT 'linked',
    "routingFallback" TEXT NOT NULL DEFAULT 'conclude',
    "minRoutingConfidence" DOUBLE PRECISION NOT NULL DEFAULT 0.6,
    "routingInstructions" TEXT,
    "costBudgetUsd" DOUBLE PRECISION,
    "accessMode" TEXT NOT NULL DEFAULT 'invitation_only',
    "publicRef" TEXT,
    "cohortId" TEXT,
    "createdBy" TEXT,
    "settings" JSONB NOT NULL DEFAULT '{}',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "app_experience_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app_experience_step" (
    "id" TEXT NOT NULL,
    "experienceId" TEXT NOT NULL,
    "key" TEXT NOT NULL,
    "kind" TEXT NOT NULL,
    "questionnaireId" TEXT,
    "versionId" TEXT,
    "roundId" TEXT,
    "title" TEXT NOT NULL,
    "purpose" TEXT,
    "selectionCriteria" TEXT,
    "ordinal" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "app_experience_step_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "app_experience_publicRef_key" ON "app_experience"("publicRef");

-- CreateIndex
CREATE INDEX "app_experience_demoClientId_idx" ON "app_experience"("demoClientId");

-- CreateIndex
CREATE INDEX "app_experience_status_idx" ON "app_experience"("status");

-- CreateIndex
CREATE INDEX "app_experience_step_experienceId_idx" ON "app_experience_step"("experienceId");

-- CreateIndex
CREATE UNIQUE INDEX "app_experience_step_experienceId_key_key" ON "app_experience_step"("experienceId", "key");

-- AddForeignKey
ALTER TABLE "app_experience" ADD CONSTRAINT "app_experience_demoClientId_fkey" FOREIGN KEY ("demoClientId") REFERENCES "app_demo_client"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app_experience_step" ADD CONSTRAINT "app_experience_step_experienceId_fkey" FOREIGN KEY ("experienceId") REFERENCES "app_experience"("id") ON DELETE CASCADE ON UPDATE CASCADE;
