/**
 * Questionnaire Pack export — Markdown serialiser.
 *
 * Renders a {@link PackModel} as a readable `.md` document: a branded title block, then whichever of
 * meta / experience-setup (one table per settings group) / data-slots / questions / definitions the
 * admin included, and a closing
 * "About ConQuest" blurb. The first Markdown serialiser in the export family — the instrument export
 * only has text and CSV — so this establishes the pattern (ATX headings, GFM tables) new export
 * builders can follow. Pure: deterministic in its input, no external Markdown library.
 */

import { QUESTION_FIDELITY_LABELS } from '@/lib/app/questionnaire/types';
import { PACK_BRAND } from '@/lib/app/questionnaire/export/pack-brand';
import type { PackModel } from '@/lib/app/questionnaire/export/build-pack-model';

/**
 * Escape the handful of characters that would otherwise break a GFM table cell. Backslashes
 * MUST be escaped before pipes: escaping `|` alone lets a value already containing `\|` (e.g.
 * a question prompt ending in a literal backslash right before a pipe) produce `\\|` in the
 * output — a GFM parser reads that as an escaped backslash followed by an UNESCAPED pipe,
 * breaking out of the cell and injecting a raw column/row boundary into the exported document.
 */
function cell(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/\|/g, '\\|').replace(/\r?\n/g, ' ').trim();
}

/** Serialise the pack model to a Markdown document. */
export function buildPackMarkdown(model: PackModel): string {
  const lines: string[] = [];

  lines.push(`# ${model.title}`);
  lines.push(`*${PACK_BRAND.tagline} — Questionnaire Pack, generated by ConQuest*`);
  lines.push('');
  lines.push(`Version ${model.versionNumber} · Generated ${model.generatedAt}`);
  lines.push('');

  if (model.meta) {
    lines.push('## Overview');
    lines.push('');
    if (model.meta.goal) lines.push(`**Goal:** ${model.meta.goal}`);
    if (model.meta.audienceSummary) lines.push(`**Audience:** ${model.meta.audienceSummary}`);
    lines.push(
      `**Contents:** ${model.sectionCount} section(s), ${model.questionCount} question(s)`
    );
    lines.push('');
  }

  if (model.setup) {
    lines.push('## Experience setup');
    lines.push('');
    // One table per group, in the order the rows arrive (the registry already sorted them) — a
    // single 60-row table is unreadable, and the group headings carry real meaning.
    let currentGroup: string | null = null;
    for (const item of model.setup) {
      if (item.group !== currentGroup) {
        if (currentGroup !== null) lines.push('');
        currentGroup = item.group;
        lines.push(`### ${currentGroup}`);
        lines.push('');
        lines.push('| Setting | Value |');
        lines.push('| --- | --- |');
      }
      lines.push(`| ${cell(item.label)} | ${cell(item.value)} |`);
    }
    lines.push('');
  }

  if (model.dataSlots) {
    lines.push('## Data slots');
    lines.push('');
    if (model.dataSlots.length === 0) {
      lines.push('_This questionnaire has no data slots yet._');
    } else {
      lines.push('| Slot | Theme | Description | Linked questions |');
      lines.push('| --- | --- | --- | --- |');
      for (const slot of model.dataSlots) {
        const questions = slot.questions.map((q) => q.prompt).join('; ');
        lines.push(
          `| ${cell(slot.name)} | ${cell(slot.theme)} | ${cell(slot.description)} | ${cell(questions)} |`
        );
      }
    }
    lines.push('');
  }

  if (model.sections) {
    lines.push('## Questions');
    lines.push('');
    if (model.sections.length === 0) {
      lines.push('_This questionnaire has no sections yet._');
    } else {
      for (const section of model.sections) {
        lines.push(`### ${section.number}. ${section.title}`);
        if (section.description) lines.push(`\n${section.description}`);
        lines.push('');
        if (section.questions.length === 0) {
          lines.push('_(no questions)_');
          lines.push('');
          continue;
        }
        for (const q of section.questions) {
          const flags = [
            q.typeLabel,
            q.required ? 'required' : 'optional',
            ...(q.fidelity ? [`fidelity: ${QUESTION_FIDELITY_LABELS[q.fidelity]}`] : []),
          ].join(', ');
          lines.push(`**${q.number}. ${q.prompt}** _(${flags})_`);
          if (q.constraint) lines.push(`- ${q.constraint}`);
          for (const option of q.options) lines.push(`- ${option}`);
          if (q.guidelines) lines.push(`- Guidance: ${q.guidelines.trim()}`);
          if (q.tags.length > 0) lines.push(`- Tags: ${q.tags.join(', ')}`);
          lines.push('');
        }
      }
    }
  }

  if (model.glossary) {
    lines.push(`## ${model.glossary.heading}`);
    lines.push('');
    for (const entry of model.glossary.entries) {
      lines.push(`**${entry.term}**`);
      entry.definitions.forEach((definition, i) => {
        lines.push(entry.definitions.length > 1 ? `${i + 1}. ${definition}` : `: ${definition}`);
      });
      lines.push('');
    }
  }

  if (model.evaluations) {
    lines.push('## Evaluation');
    lines.push('');
    lines.push(
      '*AI judge panel — includes findings not yet reviewed; treat as suggestions, not conclusions.*'
    );
    lines.push('');
    if (!model.evaluations.hasRun) {
      lines.push('_No evaluation has been run for this version yet._');
      lines.push('');
    } else {
      lines.push(
        `Last run ${model.evaluations.runAt} · ${model.evaluations.totalFindings} finding(s) across ${model.evaluations.targets.length} flagged item(s)`
      );
      lines.push('');

      // The scoreboard: how each judge rated the version. Findings are deliberately NOT repeated
      // here — they belong under the question they are about, below.
      lines.push('### Judge scores');
      lines.push('');
      for (const judge of model.evaluations.scores) {
        const verdict = judge.diagnostic
          ? `_unavailable: ${judge.diagnostic}_`
          : `${judge.score !== null ? `${Math.round(judge.score * 100)}%` : 'n/a'} · ${judge.findingCount} finding(s)`;
        lines.push(`- **${judge.label}** — ${verdict}`);
      }
      lines.push('');

      if (model.evaluations.targets.length === 0) {
        lines.push('_No findings raised._');
        lines.push('');
      } else {
        for (const target of model.evaluations.targets) {
          // The subject, named once: context chip, the prompt itself, then the judges beneath it.
          const heading = target.context
            ? `${target.context} — ${cell(target.label)}`
            : cell(target.label);
          lines.push(`### ${heading}`);
          const facts = [
            target.questionType ? `Type: ${target.questionType}` : null,
            `${target.judgeCount} judge(s)`,
            target.counts.major > 0 ? `${target.counts.major} major` : null,
            target.removed ? 'no longer in the questionnaire' : null,
          ].filter((f): f is string => f !== null);
          lines.push(`_${facts.join(' · ')}_`);
          lines.push('');
          for (const judge of target.judges) {
            lines.push(
              `- **${judge.label}** [${judge.severity} · ${judge.status}] — ${judge.proposedChange}`
            );
            lines.push(`  ${judge.rationale}`);
            if (judge.sourceQuote) lines.push(`  > ${cell(judge.sourceQuote)}`);
          }
          // The reconciled wording goes LAST, after the verdicts that produced it — it only makes
          // sense once a reader has seen what it is reconciling.
          if (target.alternatives.length > 0) {
            lines.push('');
            lines.push(
              target.alternatives.length === 1
                ? '**Suggested rewording** (addressing the judges above):'
                : '**Suggested rewordings** (addressing the judges above):'
            );
            for (const alt of target.alternatives) {
              lines.push(`- ${cell(alt.prompt)}`);
              lines.push(`  _Addresses: ${alt.addresses.join(', ')}._ ${alt.note}`);
            }
            if (target.unresolvedBy.length > 0) {
              lines.push(
                `- _Not resolved by rewording: ${target.unresolvedBy.join(', ')} — these need a structural change._`
              );
            }
          }
          lines.push('');
        }
      }
    }
  }

  if (model.adaptiveScope) {
    lines.push('## Adaptive scope');
    lines.push('');
    lines.push(
      '*How this questionnaire adapts to each respondent — which parts everyone gets, which parts depend on what they say, and the rules that decide.*'
    );
    lines.push('');
    if (!model.adaptiveScope.enabled) {
      lines.push(
        '_Adaptive scope is not enabled for this version — every respondent is asked the full instrument._'
      );
      lines.push('');
    } else {
      const facts = [
        `Up to ${model.adaptiveScope.maxConditionalTopics} conditional topic(s) per interview`,
        model.adaptiveScope.includeCheckTopic
          ? 'one additional, unselected topic is sampled lightly to check for blind spots'
          : null,
        model.adaptiveScope.sessionBudgetSeconds > 0
          ? `interviews are budgeted to about ${Math.round(model.adaptiveScope.sessionBudgetSeconds / 60)} minute(s)`
          : null,
      ].filter((f): f is string => f !== null);
      lines.push(facts.join(' · '));
      lines.push('');

      lines.push('### Always asked');
      lines.push('');
      if (model.adaptiveScope.alwaysAskedTopics.length === 0) {
        lines.push('_None defined._');
      } else {
        for (const topic of model.adaptiveScope.alwaysAskedTopics) {
          const suffix = topic.sampledOnly ? ' _(sampled lightly, not asked in full)_' : '';
          lines.push(`- **${cell(topic.label)}**${suffix}`);
          if (topic.description) lines.push(`  ${cell(topic.description)}`);
        }
      }
      lines.push('');

      lines.push('### Asked when it fits');
      lines.push('');
      if (model.adaptiveScope.conditionalTopics.length === 0) {
        lines.push('_None defined._');
      } else {
        for (const topic of model.adaptiveScope.conditionalTopics) {
          const suffix = topic.sampledOnly ? ' _(sampled lightly, not asked in full)_' : '';
          lines.push(`- **${cell(topic.label)}**${suffix}`);
          if (topic.description) lines.push(`  ${cell(topic.description)}`);
          if (topic.criteria) lines.push(`  _Included when: ${cell(topic.criteria)}_`);
        }
      }
      lines.push('');

      if (model.adaptiveScope.rules.length > 0) {
        lines.push('### Hard rules');
        lines.push('');
        for (const rule of model.adaptiveScope.rules) {
          lines.push(`- ${cell(rule.sentence)}`);
        }
        lines.push('');
      }

      const evaluation = model.adaptiveScope.evaluation;
      lines.push('### Scope evaluation');
      lines.push('');
      lines.push(
        '*AI judge panel over the routing design above — includes findings not yet reviewed; treat as suggestions, not conclusions.*'
      );
      lines.push('');
      if (!evaluation.hasRun) {
        lines.push('_No scope evaluation has been run for this version yet._');
        lines.push('');
      } else {
        lines.push(
          `Last run ${evaluation.runAt} · ${evaluation.totalFindings} finding(s) across ${evaluation.targets.length} flagged item(s)`
        );
        lines.push('');

        lines.push('| Judge | Score | Findings |');
        lines.push('| --- | --- | --- |');
        for (const judge of evaluation.scores) {
          const score = judge.diagnostic
            ? `unavailable (${cell(judge.diagnostic)})`
            : judge.score !== null
              ? `${Math.round(judge.score * 100)}%`
              : 'n/a';
          lines.push(`| ${cell(judge.label)} | ${score} | ${judge.findingCount} |`);
        }
        lines.push('');

        if (evaluation.targets.length === 0) {
          lines.push('_No findings raised._');
          lines.push('');
        } else {
          for (const target of evaluation.targets) {
            lines.push(`#### ${cell(target.label)}`);
            const facts = [
              `${target.judges.length} finding(s)`,
              target.counts.major > 0 ? `${target.counts.major} major` : null,
              target.removed ? 'no longer in the scope config' : null,
            ].filter((f): f is string => f !== null);
            lines.push(`_${facts.join(' · ')}_`);
            lines.push('');
            for (const judge of target.judges) {
              lines.push(
                `- **${judge.label}** [${judge.severity} · ${judge.status}] — ${judge.proposedChange}`
              );
              lines.push(`  ${judge.rationale}`);
              if (judge.proposedEditSummary)
                lines.push(`  Proposed edit: ${judge.proposedEditSummary}`);
              if (judge.sourceQuote) lines.push(`  > ${cell(judge.sourceQuote)}`);
            }
            lines.push('');
          }
        }
      }
    }
  }

  lines.push('---');
  lines.push('');
  lines.push(`## ${PACK_BRAND.closingHeading}`);
  lines.push('');
  lines.push(PACK_BRAND.closingBlurb);
  lines.push('');
  lines.push(`[${PACK_BRAND.website}](https://${PACK_BRAND.website})`);

  return `${lines.join('\n').trimEnd()}\n`;
}
