/**
 * Questionnaire Pack export — Markdown serialiser.
 *
 * Renders a {@link PackModel} as a readable `.md` document: a branded title block, then whichever of
 * meta / experience-setup (one table per settings group) / data-slots / questions / definitions the
 * admin included, and a closing
 * "About ConQuest" blurb. The first Markdown serialiser in the export family — the instrument export
 * only has text and CSV — so this establishes the pattern (ATX headings, GFM tables) new export
 * builders can follow. Pure: deterministic in its input, no external Markdown library.
 */

import { QUESTION_FIDELITY_LABELS, questionTypeLabel } from '@/lib/app/questionnaire/types';
import { decidedStatusLabel, findingSeverityLabel } from '@/lib/app/questionnaire/evaluation';
import { formatPackDate, PACK_BRAND } from '@/lib/app/questionnaire/export/pack-brand';
import type {
  PackConditionalTopicsTopic,
  PackModel,
} from '@/lib/app/questionnaire/export/build-pack-model';

/**
 * A judge's own line: who said it, how serious, and whether anyone has acted on it.
 *
 * Both values used to print raw (`[minor · pending]`), which is a machine's vocabulary in a
 * document written for a client. `pending` is dropped entirely: it is the state of nearly every
 * finding in an untriaged run, so saying it on every line adds a word to skip and no information.
 * The console's badge row drops it for the same reason.
 */
function judgeLine(label: string, severity: string, status: string): string {
  const decided = decidedStatusLabel(status);
  const marks = [findingSeverityLabel(severity), decided].filter(Boolean).join(' · ');
  return `**${label}** [${marks}]`;
}

/**
 * Escape the handful of characters that would otherwise break a GFM table cell. Backslashes
 * MUST be escaped before pipes: escaping `|` alone lets a value already containing `\|` (e.g.
 * a question prompt ending in a literal backslash right before a pipe) produce `\\|` in the
 * output — a GFM parser reads that as an escaped backslash followed by an UNESCAPED pipe,
 * breaking out of the cell and injecting a raw column/row boundary into the exported document.
 */
function cell(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/\|/g, '\\|').replace(/\r?\n/g, ' ').trim();
}

/** Serialise the pack model to a Markdown document. */
export function buildPackMarkdown(model: PackModel): string {
  const lines: string[] = [];

  lines.push(`# ${model.title}`);
  lines.push(`*${PACK_BRAND.tagline} — Questionnaire Pack, generated by ConQuest*`);
  lines.push('');
  lines.push(
    `Version ${model.versionNumber} · Generated ${formatPackDate(model.generatedAt) ?? model.generatedAt}`
  );
  lines.push('');

  if (model.meta) {
    lines.push('## Overview');
    lines.push('');
    if (model.meta.goal) lines.push(`**Goal:** ${model.meta.goal}`);
    if (model.meta.audienceSummary) lines.push(`**Audience:** ${model.meta.audienceSummary}`);
    lines.push(
      `**Contents:** ${model.sectionCount} section(s), ${model.questionCount} question(s)`
    );
    lines.push('');
  }

  if (model.setup) {
    lines.push('## Experience setup');
    lines.push('');
    // One table per group, in the order the rows arrive (the registry already sorted them) — a
    // single 60-row table is unreadable, and the group headings carry real meaning.
    let currentGroup: string | null = null;
    for (const item of model.setup) {
      if (item.group !== currentGroup) {
        if (currentGroup !== null) lines.push('');
        currentGroup = item.group;
        lines.push(`### ${currentGroup}`);
        lines.push('');
        lines.push('| Setting | Value |');
        lines.push('| --- | --- |');
      }
      lines.push(`| ${cell(item.label)} | ${cell(item.value)} |`);
    }
    lines.push('');
  }

  if (model.dataSlots) {
    lines.push('## Data slots');
    lines.push('');
    if (model.dataSlots.length === 0) {
      lines.push('_This questionnaire has no data slots yet._');
    } else {
      lines.push('| Slot | Theme | Description | Linked questions |');
      lines.push('| --- | --- | --- | --- |');
      for (const slot of model.dataSlots) {
        const questions = slot.questions.map((q) => q.prompt).join('; ');
        lines.push(
          `| ${cell(slot.name)} | ${cell(slot.theme)} | ${cell(slot.description)} | ${cell(questions)} |`
        );
      }
    }
    lines.push('');
  }

  if (model.sections) {
    lines.push('## Questions');
    lines.push('');
    if (model.sections.length === 0) {
      lines.push('_This questionnaire has no sections yet._');
    } else {
      for (const section of model.sections) {
        lines.push(`### ${section.number}. ${section.title}`);
        if (section.description) lines.push(`\n${section.description}`);
        lines.push('');
        if (section.questions.length === 0) {
          lines.push('_(no questions)_');
          lines.push('');
          continue;
        }
        for (const q of section.questions) {
          const flags = [
            q.typeLabel,
            q.required ? 'required' : 'optional',
            ...(q.fidelity ? [`fidelity: ${QUESTION_FIDELITY_LABELS[q.fidelity]}`] : []),
          ].join(', ');
          lines.push(`**${q.number}. ${q.prompt}** _(${flags})_`);
          if (q.constraint) lines.push(`- ${q.constraint}`);
          for (const option of q.options) lines.push(`- ${option}`);
          if (q.guidelines) lines.push(`- Guidance: ${q.guidelines.trim()}`);
          if (q.tags.length > 0) lines.push(`- Tags: ${q.tags.join(', ')}`);
          lines.push('');
        }
      }
    }
  }

  if (model.glossary) {
    lines.push(`## ${model.glossary.heading}`);
    lines.push('');
    for (const entry of model.glossary.entries) {
      lines.push(`**${entry.term}**`);
      entry.definitions.forEach((definition, i) => {
        lines.push(entry.definitions.length > 1 ? `${i + 1}. ${definition}` : `: ${definition}`);
      });
      lines.push('');
    }
  }

  if (model.evaluations) {
    lines.push('## Evaluation');
    lines.push('');
    lines.push(
      '*AI judge panel — includes findings not yet reviewed; treat as suggestions, not conclusions.*'
    );
    lines.push('');
    if (!model.evaluations.hasRun) {
      lines.push('_No evaluation has been run for this version yet._');
      lines.push('');
    } else {
      lines.push(
        `Last run ${formatPackDate(model.evaluations.runAt) ?? 'date unknown'} · ${model.evaluations.totalFindings} finding(s) across ${model.evaluations.targets.length} flagged item(s)`
      );
      lines.push('');

      // The scoreboard: how each judge rated the version. Findings are deliberately NOT repeated
      // here — they belong under the question they are about, below.
      lines.push('### Judge scores');
      lines.push('');
      for (const judge of model.evaluations.scores) {
        const verdict = judge.diagnostic
          ? `_unavailable: ${judge.diagnostic}_`
          : `${judge.score !== null ? `${Math.round(judge.score * 100)}%` : 'n/a'} · ${judge.findingCount} finding(s)`;
        lines.push(`- **${judge.label}** — ${verdict}`);
      }
      lines.push('');

      if (model.evaluations.targets.length === 0) {
        lines.push('_No findings raised._');
        lines.push('');
      } else {
        const include = model.include;

        /** The reconciled wordings, as their own lines. Used under a verdict block, or alone. */
        const pushRewordings = (target: (typeof model.evaluations.targets)[number]) => {
          for (const alt of target.alternatives) {
            lines.push(`- ${cell(alt.prompt)}`);
            lines.push(`  _Addresses: ${alt.addresses.join(', ')}._ ${alt.note}`);
          }
          if (target.unresolvedBy.length > 0) {
            lines.push(
              `- _Not resolved by rewording: ${target.unresolvedBy.join(', ')} — these need a structural change._`
            );
          }
        };

        for (const target of model.evaluations.targets) {
          // The subject, named once: context chip, the prompt itself, then the verdict beneath it.
          const heading = target.context
            ? `${target.context} — ${cell(target.label)}`
            : cell(target.label);
          lines.push(`### ${heading}`);
          const facts = [
            target.questionType ? `Type: ${questionTypeLabel(target.questionType)}` : null,
            // Who is actually asked it. A reader weighs "delete this" very differently once they
            // know only some respondents ever see it, and completely differently again when the
            // answer is nobody.
            target.routingReach
              ? target.topicLabel
                ? `${target.routingReach}: ${cell(target.topicLabel)}`
                : target.routingReach
              : null,
            `${target.judgeCount} judge(s)`,
            target.counts.major > 0 ? `${target.counts.major} major` : null,
            target.removed ? 'no longer in the questionnaire' : null,
          ].filter((f): f is string => f !== null);
          lines.push(`_${facts.join(' · ')}_`);
          lines.push('');

          // What the panel wants done, before any of the arguments for it. The appendix used to
          // open with four near-identical judge paragraphs and leave the reader to work out that
          // all four were asking for the same thing.
          const verdict = include.evaluationVerdicts ? target.verdict : null;
          // Gated on alternatives alone, matching the PDF and `EvaluationGroupVerdict`: with no
          // proposed wording, an "unresolved by" line is a caveat about something the reader was
          // never shown.
          const hasRewordings = target.alternatives.length > 0;
          if (verdict) {
            for (const block of verdict.blocks) {
              lines.push(`**${block.heading}**, as proposed by ${block.backing} — ${block.judges}`);
              // The suggestion itself, so a block still says WHY when judge reasoning is off —
              // which is the default download, and where the console would offer a tab.
              for (const suggestion of block.suggestions) lines.push(`  ${cell(suggestion)}`);
              // The wordings sit inside the block they answer. Hung off whichever action leads,
              // they would print proposed phrasing under "A deletion" — as if the panel wanted the
              // question deleted and rewritten.
              if (block.holdsWording && include.evaluationRewordings && hasRewordings) {
                // Labelled here as it is in the PDF and the console. Unlabelled, a proposed
                // phrasing sits among the block's judge suggestions as an anonymous bullet, and
                // the most copy-pasted line in the appendix reads as one more opinion.
                lines.push(
                  target.alternatives.length === 1
                    ? '  **Suggested rewording:**'
                    : '  **Suggested rewordings:**'
                );
                pushRewordings(target);
              }
              lines.push('');
            }
          }

          if (include.evaluationJudgeDetail) {
            for (const judge of target.judges) {
              lines.push(
                `- ${judgeLine(judge.label, judge.severity, judge.status)} — ${judge.proposedChange}`
              );
              lines.push(`  ${judge.rationale}`);
              // What a click would actually do, in the same words the console prints under the
              // button that does it.
              if (judge.proposedEditSummary) lines.push(`  ${judge.proposedEditSummary}`);
              if (judge.destination) lines.push(`  ${judge.destination}`);
              // The reviewer's own words — the one line on a finding written by a person.
              if (judge.applyInstruction) {
                lines.push(`  _Reviewer's instruction: ${cell(judge.applyInstruction)}_`);
              }
              if (include.evaluationEvidence && judge.sourceQuote) {
                lines.push(`  > ${cell(judge.sourceQuote)}`);
              }
            }
            lines.push('');
          }

          // No verdict to host them, so the wordings stand alone rather than being dropped — a run
          // from before the verdict step, or a download with verdicts unticked. LAST, after the
          // judges, which is where they sat before verdicts existed and for the reason that has not
          // changed: a resolution only reads as one once you have seen the disagreement.
          if (!verdict && include.evaluationRewordings && hasRewordings) {
            lines.push(
              target.alternatives.length === 1
                ? '**Suggested rewording** (addressing the judges above):'
                : '**Suggested rewordings** (addressing the judges above):'
            );
            pushRewordings(target);
            lines.push('');
          }
        }
      }
    }
  }

  if (model.conditionalTopics) {
    lines.push('## Conditional topics');
    lines.push('');
    lines.push(
      '*How this questionnaire adapts to each respondent — which parts everyone gets, which parts depend on what they say, and the rules that decide.*'
    );
    lines.push('');
    if (!model.conditionalTopics.enabled) {
      lines.push(
        '_Conditional topics is not enabled for this version — every respondent is asked the full instrument._'
      );
      lines.push('');
    } else {
      /** One topic: what it is, when it applies, and (opt-in) the questions it covers. */
      const pushTopic = (topic: PackConditionalTopicsTopic) => {
        const suffix = topic.sampledOnly ? ' _(sampled lightly, not asked in full)_' : '';
        lines.push(`- **${cell(topic.label)}**${suffix}`);
        if (topic.description) lines.push(`  ${cell(topic.description)}`);
        if (topic.criteria) lines.push(`  _Included when: ${cell(topic.criteria)}_`);
        // What the source document asked to be watched for mid-conversation. Recorded rather than
        // acted on, and said so — otherwise the document shows the approximation as the intent.
        if (topic.trigger) {
          lines.push(
            `  _The source document asks for this when: ${cell(topic.trigger.condition)}. Today it is decided from the opening instead._`
          );
        }
        for (const q of topic.questions) lines.push(`  - ${cell(q.prompt)}`);
      };

      // Derived from the routing settings registry, not hand-listed: the section named four of the
      // fifteen settings before, and the ones it missed included whether the respondent is told
      // what was chosen.
      lines.push('| Setting | Value |');
      lines.push('| --- | --- |');
      for (const item of model.conditionalTopics.settings) {
        lines.push(`| ${cell(item.label)} | ${cell(item.value)} |`);
      }
      lines.push('');

      lines.push('### Always asked');
      lines.push('');
      if (model.conditionalTopics.alwaysAsked.length === 0) {
        lines.push('_None defined._');
      } else {
        for (const topic of model.conditionalTopics.alwaysAsked) pushTopic(topic);
      }
      lines.push('');

      lines.push('### Asked when it fits');
      lines.push('');
      if (model.conditionalTopics.conditional.length === 0) {
        lines.push('_None defined._');
      } else {
        for (const topic of model.conditionalTopics.conditional) pushTopic(topic);
      }
      lines.push('');

      if (model.conditionalTopics.rules.length > 0) {
        lines.push('### Hard rules');
        lines.push('');
        for (const rule of model.conditionalTopics.rules) {
          lines.push(`- ${cell(rule.sentence)}`);
        }
        lines.push('');
      }

      // Skipped wholesale when the admin excluded it — the "has not been reviewed" line below is
      // about a version nobody has evaluated, not about a download that left the review out.
      const evaluation = model.conditionalTopics.evaluation;
      if (evaluation) {
        lines.push('### Review of this routing');
        lines.push('');
        lines.push(
          '*AI judge panel over the routing design above — includes findings not yet reviewed; treat as suggestions, not conclusions.*'
        );
        lines.push('');
        if (!evaluation.hasRun) {
          lines.push('_This routing has not been reviewed._');
          lines.push('');
        } else {
          lines.push(
            `Last run ${formatPackDate(evaluation.runAt) ?? 'date unknown'} · ${evaluation.totalFindings} finding(s) across ${evaluation.targets.length} flagged item(s)`
          );
          lines.push('');

          lines.push('| Judge | Score | Findings |');
          lines.push('| --- | --- | --- |');
          for (const judge of evaluation.scores) {
            const score = judge.diagnostic
              ? `unavailable (${cell(judge.diagnostic)})`
              : judge.score !== null
                ? `${Math.round(judge.score * 100)}%`
                : 'n/a';
            lines.push(`| ${cell(judge.label)} | ${score} | ${judge.findingCount} |`);
          }
          lines.push('');

          if (evaluation.targets.length === 0) {
            lines.push('_No findings raised._');
            lines.push('');
          } else {
            for (const target of evaluation.targets) {
              lines.push(`#### ${cell(target.label)}`);
              const facts = [
                `${target.judges.length} finding(s)`,
                target.counts.major > 0 ? `${target.counts.major} major` : null,
                target.removed ? 'no longer part of the routing' : null,
              ].filter((f): f is string => f !== null);
              lines.push(`_${facts.join(' · ')}_`);
              lines.push('');
              for (const judge of target.judges) {
                lines.push(
                  `- ${judgeLine(judge.label, judge.severity, judge.status)} — ${judge.proposedChange}`
                );
                lines.push(`  ${judge.rationale}`);
                if (judge.proposedEditSummary)
                  lines.push(`  Proposed edit: ${judge.proposedEditSummary}`);
                if (judge.sourceQuote) lines.push(`  > ${cell(judge.sourceQuote)}`);
              }
              lines.push('');
            }
          }
        }
      }
    }
  }

  // ── Interviewer policy (F18.8) ───────────────────────────────────────────
  // Above the closing blurb, with every other content section. It used to be emitted after it,
  // which put a whole appendix below the document's sign-off — invisible to anyone who stopped
  // reading where the document said it had ended.
  if (model.interviewerPolicy) {
    const p = model.interviewerPolicy;
    lines.push('## The interviewer');
    lines.push('');
    if (!p.conversational) {
      lines.push(
        '_This questionnaire is filled in as a form, so none of the interviewer settings apply._'
      );
      lines.push('');
    } else {
      lines.push(`**Questioning approach:** ${p.approachLabel}`);
      if (p.paceLabel) lines.push(`**Pace:** ${p.paceLabel}`);
      lines.push(`**Opening questions:** ${p.openingSource}`);
      if (p.tacticLabels.length > 0) lines.push(`**Tactics:** ${p.tacticLabels.join(', ')}`);
      lines.push('');

      if (p.arcBands.length > 0) {
        lines.push('### How the questioning narrows');
        lines.push('');
        for (const band of p.arcBands) lines.push(`- **${band.label}** — ${band.detail}`);
        lines.push('');
      }

      lines.push('### House rules');
      lines.push('');
      if (!p.houseRulesEnabled || p.houseRules.length === 0) {
        lines.push('_No house rules are in force for this questionnaire._');
      } else {
        for (const rule of p.houseRules) {
          const trigger = rule.trigger ? ` _(when asked about: ${rule.trigger})_` : '';
          lines.push(`- **${rule.kind}**${trigger}: ${rule.text}`);
        }
      }
      lines.push('');

      lines.push('### Questions asked as written');
      lines.push('');
      if (!p.fidelityEnabled) {
        lines.push('_Every question is asked conversationally._');
      } else {
        for (const d of p.fidelityDistribution) {
          if (d.count > 0) lines.push(`- ${d.label}: ${d.count}`);
        }
        if (p.mustAskQuestions.length > 0) {
          lines.push('');
          lines.push('Put to the respondent word for word:');
          for (const q of p.mustAskQuestions) lines.push(`- ${q.prompt}`);
        }
      }
      lines.push('');
    }

    // The judge panel's verdict, nested inside the policy it is about. `hasRun: false` still
    // renders — stating the fact beats silently having no section.
    const ev = p.evaluation;
    lines.push('### Interviewer review');
    lines.push('');
    if (!ev.hasRun) {
      lines.push('_This interviewer setup has not been reviewed._');
      lines.push('');
    } else {
      lines.push(
        `Reviewed ${formatPackDate(ev.runAt) ?? 'date unknown'} · ${ev.totalFindings} finding(s).`
      );
      lines.push('');
      lines.push('| Reviewer | Score | Findings |');
      lines.push('| --- | --- | --- |');
      for (const sc of ev.scores) {
        const score =
          sc.score === null ? (sc.diagnostic ?? 'unavailable') : `${Math.round(sc.score * 100)}%`;
        lines.push(`| ${sc.label} | ${score} | ${sc.findingCount} |`);
      }
      lines.push('');
      for (const target of ev.targets) {
        lines.push(`**${target.label}**${target.removed ? ' _(since removed)_' : ''}`);
        lines.push('');
        for (const judge of target.judges) {
          lines.push(
            `- ${judgeLine(judge.label, judge.severity, judge.status)} — ${judge.proposedChange}`
          );
          lines.push(`  - ${judge.rationale}`);
          if (judge.proposedEditSummary) lines.push(`  - Proposed: ${judge.proposedEditSummary}`);
        }
        lines.push('');
      }
    }
  }

  // The sign-off, last — every section above it is content, everything after it would be lost.
  lines.push('---');
  lines.push('');
  lines.push(`## ${PACK_BRAND.closingHeading}`);
  lines.push('');
  lines.push(PACK_BRAND.closingBlurb);
  lines.push('');
  lines.push(`[${PACK_BRAND.website}](https://${PACK_BRAND.website})`);

  return `${lines.join('\n').trimEnd()}\n`;
}
