/**
 * One attached source document.
 *
 * DELETE /api/v1/app/questionnaires/:id/versions/:vid/documents/:docId
 *   Admin-only: detach a **supplementary** document. A `primary` row is refused — it is the
 *   provenance record for the questions this version already has, and deleting it would leave the
 *   instrument claiming an origin nobody can check.
 *
 * Rate limiting is inherited from the `/api/v1/**` section cap in `proxy.ts` — a delete parses
 * nothing.
 */

import { successResponse, errorResponse } from '@/lib/api/responses';
import { getRouteLogger } from '@/lib/api/context';
import { withAdminAuth } from '@/lib/auth/guards';
import { prisma } from '@/lib/db/client';
import { getClientIP } from '@/lib/security/ip';
import { logAdminAction } from '@/lib/orchestration/audit/admin-audit-logger';

import { forkMeta, loadScopedVersion } from '@/app/api/v1/app/questionnaires/_lib/authoring-routes';
import { forkVersionIfLaunched } from '@/app/api/v1/app/questionnaires/_lib/fork';
import { listSourceDocuments } from '@/app/api/v1/app/questionnaires/_lib/source-documents';

const handleDetach = withAdminAuth<{ id: string; vid: string; docId: string }>(
  async (request, session, { params }) => {
    const { id, vid, docId } = await params;
    const log = await getRouteLogger(request);
    const clientIp = getClientIP(request);

    const scoped = await loadScopedVersion(id, vid);
    if (!scoped) {
      return errorResponse('Questionnaire version not found', { code: 'NOT_FOUND', status: 404 });
    }

    // Scoped to the version in the URL, so a document id from another questionnaire is a 404 rather
    // than a cross-tenant delete.
    const document = await prisma.appQuestionnaireSourceDocument.findFirst({
      where: { id: docId, versionId: vid },
      select: { id: true, role: true, fileName: true, fileHash: true },
    });
    if (!document) {
      return errorResponse('Document not found', { code: 'NOT_FOUND', status: 404 });
    }
    if (document.role !== 'supplementary') {
      return errorResponse('That document is what this questionnaire was built from', {
        code: 'PRIMARY_DOCUMENT',
        status: 409,
        details: {
          document: ['Only supporting documents can be removed. Re-ingest replaces the original.'],
        },
      });
    }

    const fork = await forkVersionIfLaunched(scoped, { userId: session.user.id, clientIp });
    const editId = fork.versionId;

    // On a fork the row being deleted is the COPY on the new version, not the one the URL named —
    // the original stays with the launched version, which is the point of forking. Matched on the
    // hash because ids are regenerated by the copy.
    const deleted = await prisma.appQuestionnaireSourceDocument.deleteMany({
      where:
        editId === vid
          ? { id: docId, versionId: vid, role: 'supplementary' }
          : { versionId: editId, fileHash: document.fileHash, role: 'supplementary' },
    });

    logAdminAction({
      userId: session.user.id,
      action: 'questionnaire_source_document.detach',
      entityType: 'questionnaire_version',
      entityId: editId,
      metadata: {
        questionnaireId: id,
        versionId: editId,
        fileName: document.fileName,
        deletedCount: deleted.count,
      },
      clientIp,
    });
    log.info('Supporting document detached', { versionId: editId, fileName: document.fileName });

    return successResponse({ documents: await listSourceDocuments(editId) }, forkMeta(fork));
  }
);

export const DELETE = handleDetach;
