-- F-design: how the respondent surface is DRAWN, per questionnaire version.
--
-- The third axis of the respondent surface, orthogonal to the two that already exist:
-- `respondentLayout` decides where the parts sit, `respondentChrome` decides what surrounds them,
-- and this decides what they look like — corners, rules, shadows, and how structural the client's
-- brand is. A design is CSS only and changes no DOM, so no combination of the three can cost a
-- respondent a feature.
--
-- Defaults to 'rounded' — the soft-cornered look every questionnaire has always had — so every
-- existing version renders exactly as it did before this column existed, with no backfill. An
-- unrecognised value also resolves to 'rounded' in the app layer, so a rollback cannot leave a live
-- respondent on a design that no longer has a stylesheet.
--
-- NOTE: `prisma migrate dev --create-only` also emitted DROP INDEX for the five pgvector indexes
-- (idx_ai_knowledge_chunk_search_vector, idx_knowledge_embedding, idx_message_embedding,
-- idx_app_data_slot_embedding, idx_app_question_slot_embedding) and a DROP DEFAULT on
-- ai_knowledge_chunk."searchVector". Those are phantom — Prisma cannot see the raw-SQL index
-- definitions — and applying them destroys the knowledge-base and semantic-matching indexes. They
-- have been stripped by hand, as in every other app migration here; a schema-guard test asserts
-- they never leak back in.

-- AlterTable
ALTER TABLE "app_questionnaire_config" ADD COLUMN     "respondentDesign" TEXT NOT NULL DEFAULT 'rounded';
