-- Experiences (P15.2): runs, legs, and deterministic routing rules.
--
-- NOTE: Prisma's diff engine cannot see the raw-SQL pgvector / tsvector indexes or the
-- `ai_knowledge_chunk.searchVector` generated default, so every autogenerated app migration
-- proposes dropping them. Those statements were removed by hand. Verify the 5 vector indexes
-- (idx_ai_knowledge_chunk_search_vector, idx_knowledge_embedding, idx_message_embedding,
-- idx_app_data_slot_embedding, idx_app_question_slot_embedding) still exist after applying.

-- CreateTable
CREATE TABLE "app_experience_run" (
    "id" TEXT NOT NULL,
    "experienceId" TEXT NOT NULL,
    "publicRef" TEXT,
    "status" TEXT NOT NULL DEFAULT 'active',
    "respondentUserId" TEXT,
    "cohortMemberId" TEXT,
    "currentStepId" TEXT,
    "carryOver" JSONB,
    "routingDecision" JSONB,
    "spentUsd" DOUBLE PRECISION NOT NULL DEFAULT 0,
    "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "completedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "app_experience_run_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app_experience_run_leg" (
    "id" TEXT NOT NULL,
    "runId" TEXT NOT NULL,
    "stepId" TEXT NOT NULL,
    "sessionId" TEXT NOT NULL,
    "ordinal" INTEGER NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'active',
    "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "completedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "app_experience_run_leg_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "app_experience_routing_rule" (
    "id" TEXT NOT NULL,
    "experienceId" TEXT NOT NULL,
    "dataSlotKey" TEXT NOT NULL,
    "operator" TEXT NOT NULL,
    "value" TEXT,
    "targetStepKey" TEXT NOT NULL,
    "ordinal" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "app_experience_routing_rule_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "app_experience_run_publicRef_key" ON "app_experience_run"("publicRef");

-- CreateIndex
CREATE INDEX "app_experience_run_experienceId_idx" ON "app_experience_run"("experienceId");

-- CreateIndex
CREATE INDEX "app_experience_run_status_idx" ON "app_experience_run"("status");

-- CreateIndex
CREATE INDEX "app_experience_run_respondentUserId_idx" ON "app_experience_run"("respondentUserId");

-- CreateIndex
CREATE UNIQUE INDEX "app_experience_run_leg_sessionId_key" ON "app_experience_run_leg"("sessionId");

-- CreateIndex
CREATE INDEX "app_experience_run_leg_runId_idx" ON "app_experience_run_leg"("runId");

-- CreateIndex
CREATE INDEX "app_experience_run_leg_stepId_idx" ON "app_experience_run_leg"("stepId");

-- CreateIndex
CREATE UNIQUE INDEX "app_experience_run_leg_runId_ordinal_key" ON "app_experience_run_leg"("runId", "ordinal");

-- CreateIndex
CREATE INDEX "app_experience_routing_rule_experienceId_idx" ON "app_experience_routing_rule"("experienceId");

-- AddForeignKey
ALTER TABLE "app_experience_run" ADD CONSTRAINT "app_experience_run_experienceId_fkey" FOREIGN KEY ("experienceId") REFERENCES "app_experience"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app_experience_run_leg" ADD CONSTRAINT "app_experience_run_leg_runId_fkey" FOREIGN KEY ("runId") REFERENCES "app_experience_run"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "app_experience_routing_rule" ADD CONSTRAINT "app_experience_routing_rule_experienceId_fkey" FOREIGN KEY ("experienceId") REFERENCES "app_experience"("id") ON DELETE CASCADE ON UPDATE CASCADE;
